name: CI

on: [push]

env:
  CI_RUST_TOOLCHAIN: nightly-2022-07-01

jobs:
  check:
    name: Code style and Clippy check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ env.CI_RUST_TOOLCHAIN }}
          components: rustfmt, clippy
      - name: Check code format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install python3-pip libnuma-dev python3-pyelftools
          sudo pip3 install meson ninja
      - name: Install DPDK
        run: sudo sh scripts/install.sh
      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-features --all-targets -- -D warnings
  
  # test:
  #   name: Run tests
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions-rs/toolchain@v1
  #       with:
  #         profile: minimal
  #         toolchain: ${{ env.CI_RUST_TOOLCHAIN }}
  #     - name: Install dependencies
  #       run: sudo apt install libcapstone-dev libfuse3-dev
  #     - name: Cache the Cargo dependencies
  #       uses: actions/cache@v2
  #       with:
  #         path: |
  #           ~/.cargo/bin/
  #           ~/.cargo/registry/index/
  #           ~/.cargo/registry/cache/
  #           ~/.cargo/git/db/
  #         key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
  #     - name: Test
  #       uses: actions-rs/cargo@v1
  #       with:
  #         command: test
  #         args: -- --test-threads=1

